In [ ]:
# Import library
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

# Membaca dataset
data = pd.read_csv('/content/drive/MyDrive/PCVK/data/insurance.csv')

# Menampilkan 5 data pertama
data.head()

data.info()

# Variabel bebas / fitur
X = data.drop('charges', axis=1)

# Variabel target
y = data['charges']

print("Variabel fitur:")
print(X.columns)

print("\nVariabel target:")
print(y.name)

# Mengubah data kategorikal menjadi numerik
data = pd.get_dummies(data, drop_first=True)

data.head()

X = data.drop('charges', axis=1)
y = data['charges']

X.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
Variabel fitur:
Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region'], dtype='object')

Variabel target:
charges

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,False,True,False,False,True
1,18,33.770,1,True,False,False,True,False
2,28,33.000,3,True,False,False,True,False
3,33,22.705,0,True,False,True,False,False
4,32,28.880,0,True,False,True,False,False

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Jumlah X_train:", X_train.shape)
print("Jumlah X_test :", X_test.shape)
print("Jumlah y_train:", y_train.shape)
print("Jumlah y_test :", y_test.shape)

Jumlah X_train: (1070, 8)
Jumlah X_test : (268, 8)
Jumlah y_train: (1070,)
Jumlah y_test : (268,)

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

scaler.fit_transform(X_train)

scaler.transform(X_test)

array([[ 0.40114007, -0.89153925,  0.73433626, ..., -0.56079971,
        -0.59966106, -0.5723141 ],
       [-0.23863782, -0.08946143, -0.91119211, ...,  1.78316783,
        -0.59966106, -0.5723141 ],
       [ 1.75178229, -0.60845296, -0.91119211, ...,  1.78316783,
        -0.59966106, -0.5723141 ],
       ...,
       [-0.09646495, -0.41972876, -0.08842793, ..., -0.56079971,
        -0.59966106, -0.5723141 ],
       [ 1.04091797,  2.78941026, -0.91119211, ..., -0.56079971,
         1.66760869, -0.5723141 ],
       [ 0.82765867,  0.60252728, -0.08842793, ..., -0.56079971,
        -0.59966106,  1.74729228]])

In [ ]:
from sklearn.linear_model import LinearRegression

model_lr = LinearRegression()

In [ ]:
model_lr.fit(X_train, y_train)

y_pred_lr = model_lr.predict(X_test)

hasil_prediksi = pd.DataFrame({
    'Aktual': y_test.values,
    'Prediksi': y_pred_lr
})

hasil_prediksi.head(10)

        Aktual      Prediksi
0   9095.06825   8969.550274
1   5272.17580   7068.747443
2  29330.98315  36858.410912
3   9301.89355   9454.678501
4  33750.29180  26973.173457
5   4536.25900  10864.113164
6   2117.33885    170.280841
7  14210.53595  16903.450287
8   3732.62510   1092.430936
9  10264.44210  11218.343184

In [ ]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

r2_lr = r2_score(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
mae_lr = mean_absolute_error(y_test, y_pred_lr)

print("Hasil Evaluasi Linear Regression")
print("R-Squared :", r2_lr)
print("MSE       :", mse_lr)
print("MAE       :", mae_lr)

Hasil Evaluasi Linear Regression
R-Squared : 0.7835929767120724
MSE       : 33596915.85136145
MAE       : 4181.19447375365

In [ ]:
from sklearn.svm import SVR

model_svr = SVR()

model_svr.fit(X_train_scaled, y_train)

y_pred_svr = model_svr.predict(X_test_scaled)

r2_svr = r2_score(y_test, y_pred_svr)
mse_svr = mean_squared_error(y_test, y_pred_svr)
mae_svr = mean_absolute_error(y_test, y_pred_svr)

print("Hasil Evaluasi SVR")
print("R-Squared :", r2_svr)
print("MSE       :", mse_svr)
print("MAE       :", mae_svr)

Hasil Evaluasi SVR
R-Squared : -0.07008155372454805
MSE       : 166128803.80848217
MAE       : 8612.408423351833

In [ ]:
from sklearn.model_selection import GridSearchCV

parameter = {
    'C': [1, 10, 100, 1000],
    'gamma': ['scale', 0.01, 0.1, 1],
    'epsilon': [0.1, 0.2, 0.5, 1]
}

grid_search = GridSearchCV(
    SVR(),
    parameter,
    cv=5,
    scoring='r2'
)

grid_search.fit(X_train_scaled, y_train)

print("Parameter terbaik:")
print(grid_search.best_params_)

model_svr_tuned = grid_search.best_estimator_

y_pred_svr_tuned = model_svr_tuned.predict(X_test_scaled)

r2_svr_tuned = r2_score(y_test, y_pred_svr_tuned)
mse_svr_tuned = mean_squared_error(y_test, y_pred_svr_tuned)
mae_svr_tuned = mean_absolute_error(y_test, y_pred_svr_tuned)

print("Hasil Evaluasi SVR Setelah Tuning")
print("R-Squared :", r2_svr_tuned)
print("MSE       :", mse_svr_tuned)
print("MAE       :", mae_svr_tuned)

Parameter terbaik:
{'C': 1000, 'epsilon': 0.1, 'gamma': 0.1}
Hasil Evaluasi SVR Setelah Tuning
R-Squared : 0.7581169811842692
MSE       : 37552031.840543
MAE       : 2736.589013161129

In [ ]:
hasil = pd.DataFrame({
    'Model': [
        'Linear Regression',
        'SVR',
        'SVR Tuning'
    ],

    'R-Squared': [
        r2_lr,
        r2_svr,
        r2_svr_tuned
    ],

    'MSE': [
        mse_lr,
        mse_svr,
        mse_svr_tuned
    ],

    'MAE': [
        mae_lr,
        mae_svr,
        mae_svr_tuned
    ]
})

hasil

               Model  R-Squared           MSE          MAE
0  Linear Regression   0.783593  3.359692e+07  4181.194474
1                SVR  -0.070082  1.661288e+08  8612.408423
2         SVR Tuning   0.758117  3.755203e+07  2736.589013